Add validations

diff --git a/actions/crunchy/action.yml b/actions/crunchy/action.yml
--- a/actions/crunchy/action.yml
+++ b/actions/crunchy/action.yml
@@ -90,6 +90,21 @@ runs:
         RELEASE_NAME=pg-$(echo -n "${{github.event.repository.name}}" | md5sum | cut -c 1-8)
         echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_OUTPUT
         echo "Release name: ${RELEASE_NAME}"
+
+    - name: Validate Values File
+      shell: bash
+      run: |
+        if [ -n "${{ inputs.values }}" ]; then
+          if [ -f "$GITHUB_WORKSPACE/${{ inputs.values }}" ]; then
+            echo "Values file '${{ inputs.values }}' found."
+          else
+            echo "Error: Specified values file '${{ inputs.values }}' not found."
+            exit 1
+          fi
+        else
+          echo "No values file specified. Using default values.yaml in the chart directory."
+        fi
+
     - name: Deploy Database
       uses: bcgov/action-oc-runner@v1.2.0
       with:
@@ -194,4 +209,3 @@ runs:
           if [ "$SECRET_FOUND" = false ]; then
             echo "Error: Secret ${{steps.release_name.outputs.RELEASE_NAME}}-crunchy-pguser-app-${{ github.event.number }} was not created after 5 attempts."
             exit 1
-          fi
