Pass in needs object

diff --git a/.github/workflows/.checkNeeds.yml b/.github/workflows/.checkNeeds.yml
--- a/.github/workflows/.checkNeeds.yml
+++ b/.github/workflows/.checkNeeds.yml
@@ -2,18 +2,25 @@ name: .Helm Deployer
 
 on:
   workflow_call:
-    ### Nothing Required!
+    inputs:
+      ### Required
+      needs:
+        description: Object required to assess needs (previous jobs)
+        required: true
+        type: string
 
 jobs:
   results:
     name: Results
     runs-on: ubuntu-22.04
     steps:
-      - if: needs.deploys.outputs.triggered == 'true'
-        run: echo "Success!"
+      # - if: needs.deploys.outputs.triggered == 'true'
+      #   run: echo "Success!"
 
-      - if: needs.deploys.outputs.triggered != 'true'
-        run: |
-          # Handle fail
-          echo "needs.deploys == ${{ toJson(needs.deploys) }}"
-          exit 1
+      # - if: needs.deploys.outputs.triggered != 'true'
+      #   run: |
+      #     # Handle fail
+      #     echo "needs.deploys == ${{ toJson(needs.deploys) }}"
+      #     exit 1
+
+      - run: echo "needs == ${{ toJson(inputs.needs) }}"
