chore(ci): crunchy installer action (#142)
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>
Co-authored-by: OMPRAKASH MISHRA <omprakashmishra3978@gmail.com>

diff --git a/.github/workflows/.deployer-db.yml b/.github/workflows/.deployer-db.yml
--- a/.github/workflows/.deployer-db.yml
+++ b/.github/workflows/.deployer-db.yml
@@ -121,9 +121,27 @@ jobs:
                 --set-string crunchy.pgBackRest.s3.secretKey=${{ secrets.s3_secret_key }} \
                 --set-string crunchy.pgBackRest.s3.bucket=${{ secrets.s3_bucket }} \
                 --set-string crunchy.pgBackRest.s3.endpoint=${{ secrets.s3_endpoint }} \
-                --values ${{ inputs.values }} postgres  .
+                --values ${{ inputs.values }} ${{github.event.repository.name}}  .
             else
-              helm upgrade --install --wait --values ${{ inputs.values }} postgres .
+              helm upgrade --install --wait --values ${{ inputs.values }} ${{github.event.repository.name}} .
+            fi
+            # check if operator deployed the db successfully, retry 10 times with 60 seconds interval
+            READY=false
+            for i in {1..10}; do
+              # Check if the 'db' instance has at least 1 ready replica
+              if oc get PostgresCluster/${{github.event.repository.name}}-crunchy -o json | jq -e '.status.instances[] | select(.name=="db") | .readyReplicas > 0' > /dev/null 2>&1; then
+                echo "Crunchy DB instance 'db' is ready "
+                READY=true
+                break
+              else
+                echo "Attempt $i: Crunchy DB is not ready, waiting for 60 seconds"
+                sleep 60
+              fi
+            done
+
+            if [ "$READY" = false ]; then
+              echo "Crunchy DB did not become ready after 10 attempts."
+              exit 1
             fi
 
       - name: Add PR specific user to Crunchy DB # only for PRs
@@ -137,7 +155,7 @@ jobs:
           commands: |
             echo 'Adding PR specific user to Crunchy DB'
             NEW_USER='{"databases":["app-${{ github.event.number }}"],"name":"app-${{ github.event.number }}"}'
-            CURRENT_USERS=$(oc get PostgresCluster/postgres-crunchy -o json | jq '.spec.users')
+            CURRENT_USERS=$(oc get PostgresCluster/${{github.event.repository.name}}-crunchy -o json | jq '.spec.users')
             echo "${CURRENT_USERS}"
 
             # check if current_users already contains the new_user
@@ -148,16 +166,23 @@ jobs:
 
             UPDATED_USERS=$(echo "${CURRENT_USERS}" | jq --argjson NEW_USER "${NEW_USER}" '. + [$NEW_USER]')
             PATCH_JSON=$(jq -n --argjson users "${UPDATED_USERS}" '{"spec": {"users": $users}}')
-            oc patch PostgresCluster/postgres-crunchy --type=merge -p "${PATCH_JSON}"
+            oc patch PostgresCluster/${{github.event.repository.name}}-crunchy --type=merge -p "${PATCH_JSON}"
 
             # wait for sometime as it takes time to create the user, query the secret and check if it is created, otherwise wait in a loop for 5 rounds
+            SECRET_FOUND=false
             for i in {1..5}; do
-            if oc get secret postgres-crunchy-pguser-app-${{ github.event.number }} -o jsonpath='{.metadata.name}' > /dev/null; then
+              if oc get secret ${{github.event.repository.name}}-crunchy-pguser-app-${{ github.event.number }} -o jsonpath='{.metadata.name}' > /dev/null 2>&1; then
                 echo "Secret created"
+                SECRET_FOUND=true
                 break
-            else
-                echo "Secret not created, waiting for 60 seconds"
+              else
+                echo "Attempt $i: Secret not created, waiting for 60 seconds"
                 sleep 60
-            fi
+              fi
             done
+
+            if [ "$SECRET_FOUND" = false ]; then
+              echo "Error: Secret ${{github.event.repository.name}}-crunchy-pguser-app-${{ github.event.number }} was not created after 5 attempts."
+              exit 1
+            fi
 
