chore(ci): keep using action-oc-runner (#118)

diff --git a/.github/workflows/.deployer.yml b/.github/workflows/.deployer.yml
--- a/.github/workflows/.deployer.yml
+++ b/.github/workflows/.deployer.yml
@@ -71,35 +71,28 @@ jobs:
     environment: ${{ inputs.environment }}
     runs-on: ubuntu-24.04
     outputs:
-      triggered: ${{ steps.triggers.outputs.triggered }}
+      triggered: ${{ steps.deploy.outputs.triggered }}
     steps:
       ### Triggers, tag and release
 
-      # Check triggers (omitted or matched) for deployment
-      - uses: bcgov/action-diff-triggers@v0.2.0
-        id: triggers
-        with:
-          triggers: ${{ inputs.triggers }}
-
       # Variables
-      - if: steps.triggers.outputs.triggered == 'true' &&  inputs.tag  == ''
+      - if: inputs.tag  == ''
         id: pr
         uses: bcgov/action-get-pr@v0.0.1
-      - if: steps.triggers.outputs.triggered == 'true'
+
+      - name: Vars
         id: vars
         run: |
-          # Vars: tag and release
-
           # Tag defaults to PR number, but can be overridden by inputs.tag
           tag=${{ inputs.tag || steps.pr.outputs.pr }}
 
           # Release name includes run numbers to ensure uniqueness
-          release=${{ github.event.repository.name }}-${{ inputs.environment || steps.pr.outputs.pr || inputs.tag }}
+          release=${{ github.event.repository.name }}-${{ inputs.environment || inputs.tag || steps.pr.outputs.pr }}
           
-          # version, to support helm packaging for non-pr based releases (workflow_dispatch). default to 1.0.0+github run number
-          version=1.0.0+${{ github.run_number }}
+          # Version, used for non-PR releases
+          version=1.0.0-${{ github.run_number }}
           
-            # Summary
+          # Summary
           echo "tag=${tag}"
           echo "release=${release}"
           echo "version=${version}"
@@ -110,81 +103,51 @@ jobs:
           echo "version=${version}" >> $GITHUB_OUTPUT
 
       ### Deploy
-      - name: Install CLI tools from OpenShift Mirror
+      - name: Interrupt deployments (PR only)
+        if: github.event_name == 'pull_request'
         uses: bcgov/action-oc-runner@v0.3.0
         with:
           oc_namespace: ${{ secrets.oc_namespace }}
           oc_token: ${{ secrets.oc_token }}
           oc_server: ${{ inputs.oc_server }}
+          triggers: ${{ inputs.triggers }}
+          commands: |
+            # Interrupt any previous deployments (PR only)
+            PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
+            if [[ ${PREVIOUS} =~ pending ]]; then
+              echo "Rollback triggered"
+              helm rollback ${{ steps.vars.outputs.release }} || \
+                helm uninstall ${{ steps.vars.outputs.release }}
+            fi
 
-      # OC login and acquire short lived token
-      - if: steps.triggers.outputs.triggered == 'true'
-        shell: bash
-        run: |
-          # OC Login
-          OC_TEMP_TOKEN=$(curl -k -X POST ${{ inputs.oc_server }}/api/v1/namespaces/${{ secrets.oc_namespace }}/serviceaccounts/pipeline/token --header "Authorization: Bearer ${{ secrets.oc_token }}" -d '{"spec": {"expirationSeconds": 600}}' -H 'Content-Type: application/json; charset=utf-8' | jq -r '.status.token' )
+      - name: Deploy Helm chart
+        id: deploy
+        uses: bcgov/action-oc-runner@v0.3.0
+        with:
+          oc_namespace: ${{ secrets.oc_namespace }}
+          oc_token: ${{ secrets.oc_token }}
+          oc_server: ${{ inputs.oc_server }}
+          triggers: ${{ inputs.triggers }}
+          commands: |
+            # Package Helm chart
+            cd ${{ inputs.directory }}
+            sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
+            helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" \
+              --version=${{ steps.pr.outputs.pr || steps.vars.outputs.version }}
 
-          oc login --token=$OC_TEMP_TOKEN --server=${{ inputs.oc_server }}
-          oc project ${{ secrets.oc_namespace }} # Safeguard!
+            # Helm upgrade/rollout
+            helm upgrade \
+              --set-string global.repository=${{ github.repository }} \
+              --set-string global.tag=${{ steps.vars.outputs.tag }} \
+              ${{ inputs.params }} \
+              --install --wait ${{ inputs.atomic == 'true' && '--atomic' || ''}} \
+              ${{ steps.vars.outputs.release }} \
+              --timeout ${{ inputs.timeout-minutes }}m \
+              --values ${{ inputs.values }} \
+              ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr || steps.vars.outputs.version }}.tgz
 
-      # Only stop pre-existing deployments on PRs (status = pending-upgrade)
-      - if: steps.triggers.outputs.triggered == 'true' && github.event_name == 'pull_request'
-        run: |
-          # Interrupt any previous deployments (PR only)
-          PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
-          if [[ ${PREVIOUS} =~ pending ]]; then
-            echo "Rollback triggered"
-            helm rollback ${{ steps.vars.outputs.release }} || \
-              helm uninstall ${{ steps.vars.outputs.release }}
-          fi
+            # Helm release history
+            helm history ${{ steps.vars.outputs.release }}
 
-      # Package Helm chart
-      - if: steps.triggers.outputs.triggered == 'true'
-        uses: actions/checkout@v4
-      - if: steps.triggers.outputs.triggered == 'true'
-        working-directory: ${{ inputs.directory }}
-        run: |
-          # Helm package
-          sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
-          helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" --version=${{ steps.pr.outputs.pr || steps.vars.outputs.version }}
-
-      # Deploy Helm chart as atomic, with timeout
-      - if: steps.triggers.outputs.triggered == 'true' && inputs.atomic != 'false'
-        working-directory: ${{ inputs.directory }}
-        run: |
-          # Helm upgrade/rollout - atomic, timeout
-          helm upgrade \
-            --set-string global.repository=${{ github.repository }} \
-            --set-string global.tag=${{ steps.vars.outputs.tag }} \
-            ${{ inputs.params }} \
-            --install --wait --atomic ${{ steps.vars.outputs.release }} \
-            --timeout ${{ inputs.timeout-minutes }}m \
-            --values ${{ inputs.values }} \
-            ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr || steps.vars.outputs.version }}.tgz
-
-      # Deploy Helm chart without atomic or timeout
-      - if: steps.triggers.outputs.triggered == 'true' && inputs.atomic == 'false'
-        working-directory: ${{ inputs.directory }}
-        run: |
-          # Helm upgrade/rollout - non-atomic, no timeout
-          helm upgrade \
-            --set-string global.repository=${{ github.repository }} \
-            --set-string global.tag=${{ steps.vars.outputs.tag }} \
-            ${{ inputs.params }} \
-            ${{ steps.vars.outputs.release }} \
-            --install --wait --values ${{ inputs.values }} \
-            ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr || steps.vars.outputs.version }}.tgz
-
-      # Helm release history
-      - if: steps.triggers.outputs.triggered == 'true'
-        run: |
-          # Helm release history
-          helm history ${{ steps.vars.outputs.release }}
-
-      ### Cleanup
-
-      # Completed pod cleanup
-      - if: steps.triggers.outputs.triggered == 'true'
-        run: |
-          # Completed pod cleanup
-          oc delete po --field-selector=status.phase==Succeeded || true
+            # Completed pod cleanup
+            oc delete po --field-selector=status.phase==Succeeded || true
diff --git a/.github/workflows/.pr-close.yml b/.github/workflows/.pr-close.yml
--- a/.github/workflows/.pr-close.yml
+++ b/.github/workflows/.pr-close.yml
@@ -112,43 +112,44 @@ jobs:
     runs-on: ubuntu-24.04
     timeout-minutes: 10
     steps:
-      # OC setup
-      - uses: redhat-actions/openshift-tools-installer@v1
-        with:
-          oc: "4.14.37"
-
-      # OC Login
-      - run: |
-          # OC Login
-          oc login --token=${{ secrets.oc_token }} --server=${{ inputs.oc_server }}
-          oc project ${{ secrets.oc_namespace }} # Safeguard!
-
-      # Cleanup for Helm deployments
-      - name: Helm
-        if: inputs.cleanup == 'helm'
+      - name: Helm Cleanup
         env:
           release: ${{ inputs.repository }}-${{ inputs.target }}
-        run: |
-          # Helm cleanup steps
+        if: inputs.cleanup == 'helm'
+        uses: bcgov/action-oc-runner@v0.3.0
+        with:
+          oc_namespace: ${{ secrets.oc_namespace }}
+          oc_token: ${{ secrets.oc_token }}
+          oc_server: ${{ inputs.oc_server }}
+          command: |
+            # Cleanup for Helm deployments
 
-          # If found, then remove
-          helm status ${{ env.release }} && helm uninstall --no-hooks ${{ env.release }} || \
-            echo "Not found: ${{ env.release }}"
+            # If found, then remove
+            helm status ${{ env.release }} && helm uninstall --no-hooks ${{ env.release }} || \
+              echo "Not found: ${{ env.release }}"
       
-      # Cleanup for OpenShift template deployments, uses labels
-      - name: Label
+      - name: OC Template (label) Cleanup
         if: inputs.cleanup == 'label'
-        run: |
-          # OC Template cleanup steps
+        uses: bcgov/action-oc-runner@v0.3.0
+        with:
+          oc_namespace: ${{ secrets.oc_namespace }}
+          oc_token: ${{ secrets.oc_token }}
+          oc_server: ${{ inputs.oc_server }}
+          command: |
+            # Cleanup for OpenShift template deployments, uses labels
 
-          # Remove old build runs, build pods and deployment pods
-          oc delete all,cm,pvc,secret -l app=${{ inputs.cleanup_name }}-${{ inputs.target }}
+            # Remove old build runs, build pods and deployment pods
+            oc delete all,cm,pvc,secret -l app=${{ inputs.cleanup_name }}-${{ inputs.target }}
 
-      # Remove PVCs from OpenShift when PR closed
       - name: Remove PVCs
         if: inputs.remove_pvc
-        run: |
-          # Remove PVCs
-          echo "${{ inputs.remove_pvc }}" | while IFS= read -r pvc; do
-              oc delete pvc ${pvc//,/} || echo "Not found: ${pvc//,/}"
-          done
+        uses: bcgov/action-oc-runner@v0.3.0
+        with:
+          oc_namespace: ${{ secrets.oc_namespace }}
+          oc_token: ${{ secrets.oc_token }}
+          oc_server: ${{ inputs.oc_server }}
+          command: |
+            # Remove PVCs from OpenShift when PR closed
+            echo "${{ inputs.remove_pvc }}" | while IFS= read -r pvc; do
+                oc delete pvc ${pvc//,/} || echo "Not found: ${pvc//,/}"
+            done
