fix: Helm triggers (#28)

diff --git a/.github/workflows/.deployer.yml b/.github/workflows/.deployer.yml
--- a/.github/workflows/.deployer.yml
+++ b/.github/workflows/.deployer.yml
@@ -68,87 +68,91 @@ jobs:
     outputs:
       tag: ${{ steps.triggers.outputs.triggered }}
     steps:
-    ### Triggers, tags and early exits
+      ### Triggers, tag and release
 
-    # Check triggers (omitted or matched), exiting successfully if not fired/required
-    - uses: bcgov-nr/action-diff-triggers@v0.2.0
-      id: triggers
-      with:
-        triggers: ${{ inputs.triggers }}
-    - if: steps.triggers.outputs.triggered == 'false'
-      run: |
-        echo "No deployment required/triggered!"
-        exit 0
+      # Check triggers (omitted or matched) for deployment
+      - uses: bcgov-nr/action-diff-triggers@v0.2.0
+        id: triggers
+        with:
+          triggers: ${{ inputs.triggers }}
 
-    # Variables
-    - id: pr
-      uses: bcgov-nr/action-get-pr@v0.0.1
-    - id: vars
-      run: |
-        # Vars: tag and release
+      # Variables
+      - if: steps.triggers.outputs.triggered == 'true'
+        id: pr
+        uses: bcgov-nr/action-get-pr@v0.0.1
+      - if: steps.triggers.outputs.triggered == 'true'
+        id: vars
+        run: |
+          # Vars: tag and release
 
-        # Tag defaults to PR number, but can be overridden by inputs.tag
-        tag=${{ inputs.tag || steps.pr.outputs.pr }}
+          # Tag defaults to PR number, but can be overridden by inputs.tag
+          tag=${{ inputs.tag || steps.pr.outputs.pr }}
 
-        # Release name includes run numbers to ensure uniqueness
-        release=${{ github.event.repository.name }}-${{ inputs.environment || steps.pr.outputs.pr }}
+          # Release name includes run numbers to ensure uniqueness
+          release=${{ github.event.repository.name }}-${{ inputs.environment || steps.pr.outputs.pr }}
 
-        # Summary
-        echo "tag=${tag}"
-        echo "release=${release}"
+          # Summary
+          echo "tag=${tag}"
+          echo "release=${release}"
 
-        # Output
-        echo "tag=${tag}" >> $GITHUB_OUTPUT
-        echo "release=${release}" >> $GITHUB_OUTPUT
+          # Output
+          echo "tag=${tag}" >> $GITHUB_OUTPUT
+          echo "release=${release}" >> $GITHUB_OUTPUT
 
-    ### Deploy
+      ### Deploy
 
-    # OC Login
-    - run: |
-        # OC Login
-        oc login --token=${{ secrets.oc_token }} --server=${{ inputs.oc_server }}
-        oc project ${{ secrets.oc_namespace }} # Safeguard!
+      # OC Login
+      - if: steps.triggers.outputs.triggered == 'true'
+        run: |
+          # OC Login
+          oc login --token=${{ secrets.oc_token }} --server=${{ inputs.oc_server }}
+          oc project ${{ secrets.oc_namespace }} # Safeguard!
 
-    # Only stop pre-existing deployments on PRs
-    - if: github.event_name == 'pull_request'
-      run: |
-        # Interrupt any previous PR deployments (status = pending-upgrade)
-        PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
-        if [[ ${PREVIOUS} =~ pending ]]; then
-          echo "Rollback triggered"
-          helm rollback ${{ steps.vars.outputs.release }} || \
-            helm uninstall ${{ steps.vars.outputs.release }}
-        fi
+      # Only stop pre-existing deployments on PRs (status = pending-upgrade)
+      - if: steps.triggers.outputs.triggered == 'true' && github.event_name == 'pull_request'
+        run: |
+          # Interrupt any previous deployments (PR only)
+          PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
+          if [[ ${PREVIOUS} =~ pending ]]; then
+            echo "Rollback triggered"
+            helm rollback ${{ steps.vars.outputs.release }} || \
+              helm uninstall ${{ steps.vars.outputs.release }}
+          fi
 
-    # Package Helm chart
-    - uses: actions/checkout@v4
-    - working-directory: ${{ inputs.directory }}
-      run: |
-        # Package Helm chart using release name
-        sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
-        helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" --version=${{ steps.pr.outputs.pr }}
+      # Package Helm chart
+      - if: steps.triggers.outputs.triggered == 'true'
+        uses: actions/checkout@v4
+      - if: steps.triggers.outputs.triggered == 'true'
+        working-directory: ${{ inputs.directory }}
+        run: |
+          # Helm package
+          sed -i 's/^name:.*/name: ${{ github.event.repository.name }}/' Chart.yaml
+          helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" --version=${{ steps.pr.outputs.pr }}
 
-    # Deploy Helm chart
-    - working-directory: ${{ inputs.directory }}
-      run: |
-        # Deploy Helm chart
-        helm upgrade \
-          --set-string global.repository=${{ github.repository }} \
-          --set-string global.tag=${{ steps.vars.outputs.tag }} \
-          ${{ inputs.params }} \
-          --install --wait --atomic ${{ steps.vars.outputs.release }} \
-          --timeout ${{ inputs.timeout-minutes }}m \
-          --values ${{ inputs.values }} \
-          ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr }}.tgz
+      # Deploy Helm chart
+      - if: steps.triggers.outputs.triggered == 'true'
+        working-directory: ${{ inputs.directory }}
+        run: |
+          # Helm upgrade/rollout
+          helm upgrade \
+            --set-string global.repository=${{ github.repository }} \
+            --set-string global.tag=${{ steps.vars.outputs.tag }} \
+            ${{ inputs.params }} \
+            --install --wait --atomic ${{ steps.vars.outputs.release }} \
+            --timeout ${{ inputs.timeout-minutes }}m \
+            --values ${{ inputs.values }} \
+            ./${{ github.event.repository.name }}-${{ steps.pr.outputs.pr }}.tgz
 
-    # Helm release history
-    - run: |
-        # Helm release history
-        helm history ${{ steps.vars.outputs.release }}
+      # Helm release history
+      - if: steps.triggers.outputs.triggered == 'true'
+        run: |
+          # Helm release history
+          helm history ${{ steps.vars.outputs.release }}
 
-    ### Cleanup
+      ### Cleanup
 
-    # Completed pod cleanup
-    - run: |
-        # Expand for succeeded pod cleanup (optional)
-        oc delete po --field-selector=status.phase==Succeeded || true
+      # Completed pod cleanup
+      - if: steps.triggers.outputs.triggered == 'true'
+        run: |
+          # Completed pod cleanup
+          oc delete po --field-selector=status.phase==Succeeded || true
