Juggle steps

diff --git a/.github/workflows/.pr-validate.yml b/.github/workflows/.pr-validate.yml
--- a/.github/workflows/.pr-validate.yml
+++ b/.github/workflows/.pr-validate.yml
@@ -9,7 +9,7 @@ on:
         default: 'true'
         required: false
         type: string
-      forks_allowed:
+      reject_forks:
         description: 'Are forks allowed?  [true|false]'
         default: 'false'
         required: false
@@ -29,22 +29,15 @@ jobs:
         if: inputs.conventional_commits != 'false'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - if: failure()
-        run: |
-          echo "Please use conventional commits in your PR title and re-run this job."
-          echo "https://www.conventionalcommits.org/en/v1.0.0/"
-          exit 1
 
-      # Block forks
-      - name: Block Forks
-        if: inputs.forks_allowed != 'true' && github.event.pull_request.head.repo.fork
-        run: |
-          echo "These workflows do not work with forks.  Our apologies for any inconvenience."
-          exit 1
+      # Check for forks
+      - name: Fork Check
+        if: inputs.reject_forks != 'true' && github.event.pull_request.head.repo.fork
+        run: exit 1
 
       # Add PR Description, doesn't work with forks
-      - name: Add PR Description
-        if: inputs.forks_allowed != 'true' && inputs.markdown_links != ''
+      - name: PR Description
+        if: inputs.reject_forks != 'true' && inputs.markdown_links != ''
         uses: bcgov-nr/action-pr-description-add@v1.1.1
         env:
           DOMAIN: apps.silver.devops.gov.bc.ca
@@ -63,3 +56,13 @@ jobs:
 
             After merge, new images are deployed in:
             - [Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge.yml)
+
+      # Notify of any failures
+      - name: Errors
+        if: failure()
+        run: |
+          echo "Validation failed!  Possible reasons:"
+          echo " - Forks are not supported"
+          echo " - Conventional commits required for PR titles and merges"
+          echo "    https://www.conventionalcommits.org/en/v1.0.0/"
+          exit 1
