Catch trailing commas

diff --git a/.github/workflows/.pr-close.yml b/.github/workflows/.pr-close.yml
--- a/.github/workflows/.pr-close.yml
+++ b/.github/workflows/.pr-close.yml
@@ -174,5 +174,5 @@ jobs:
         run: |
           # Remove PVCs
           echo "${{ inputs.remove_pvc }}" | while IFS= read -r pvc; do
-              oc delete pvc ${pvc//,/} || echo "Not found: $pvc"
+              oc delete pvc ${pvc//,/} || echo "Not found: ${pvc//,/}"
           done
