chore: compare before and after tags in pr-open

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -32,6 +32,16 @@ jobs:
           target: latest
           tags: ${{ github.event.number }}
 
+      - run: |
+          # Verify tagging
+          INSPECT="docker manifest inspect ghcr.io/${{ inputs.organization }}/${{ inputs.repository }}/${{ matrix.package }}"
+          SOURCE=$(${INSPECT}:${{ inputs.tag_promote }} | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
+          TARGET=$(${INSPECT}:${{ inputs.target }} | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
+          if [ "${SOURCE}" != "${TARGET}" ]; then
+            echo "ERROR: Tagging failed!"
+            exit 1
+          fi
+
   deploys:
     name: Deploys
     needs: [builds, validate]
