chore(ci): fix merge problem (#139)

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -58,7 +58,7 @@ jobs:
       promote_images: backend frontend migrations
       promote_tags: pr
 
-  cert_generation: # testing, will be deleted
+  csr-generator: # testing, will be deleted
     name: Certificate Generation
     uses: ./.github/workflows/csr-generator.yml
     secrets:
@@ -70,14 +70,17 @@ jobs:
 
   results:
     name: Results
-    needs: [deploys, schema-spy, validate]
+    needs: [builds, csr-generator, deploys, schema-spy, validate]
     runs-on: ubuntu-24.04
     steps:
-      - if: needs.deploys.outputs.triggered == 'true'
-        run: echo "Success!"
+      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
+        run: echo "At least one job has failed." && exit 1
 
-      - if: needs.deploys.outputs.triggered != 'true'
-        run: |
-          # Handle fail
-          echo "needs.deploys == ${{ toJson(needs.deploys) }}"
-          exit 1
+      - if: needs.deploys.outputs.triggered == 'true'
+        run: echo "Deploy triggered successfully!"
+
+      # - if: needs.deploys.outputs.triggered != 'true'
+      #   run: |
+      #     # Handle fail
+      #     echo "needs.deploys == ${{ toJson(needs.deploys) }}"
+      #     exit 1
