Add check for outputs

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -40,9 +40,16 @@ jobs:
       oc_namespace: ${{ secrets.oc_namespace }}
       oc_token: ${{ secrets.oc_token }}
 
-  outputs:
-    name: Outputs
+  results:
+    name: Results
     needs: [deploys]
     runs-on: ubuntu-22.04
     steps:
-      - run: echo "needs.deploys == ${{ toJson(needs.deploys) }}"
+      - if: needs.deploys.outputs.triggered == 'true'
+        run: echo "Success!"
+
+      - if: needs.deploys.outputs.triggered != 'true'
+        run: |
+          # Handle fail
+          echo "needs.deploys == ${{ toJson(needs.deploys) }}"
+          exit 1
